### ISSUE TITLE
Unable to Parse

### ISSUE THREAD

**Issue by afterconnery** [zecwalletco/zecwallet-mobile#1]
Running Android 7.1.1
I am able to sideload apps.
I get this screen when i try and open the apk file.

![Screenshot_20200527-183830](https://user-images.githubusercontent.com/10703247/83081244-3082e780-a04e-11ea-97ed-16ce2c232f05.png)

**Comment by adityapk00** [comment]
Thanks for reporting this. It looks like the App is targeting API v26 (Android 8.0 Oreo). Let me look into how to get to Android 7

**Comment by adityapk00** [comment]
I added a fix that should work. I'll make a new release tomorrow with the updated APK.
