### ISSUE TITLE
Unable to send amount less than 1 ZEC

### ISSUE THREAD

**Issue by rex4539** [zecwalletco/zecwallet-mobile#15]
If you try to type anything less than 1 ZEC, you get "Invalid Amount" error.

**Comment by BostonZcash** [comment]
What is your device's locale using as a decimal separator, a period or a comma, and which are you typing in?

**Comment by rex4539** [comment]
![image](https://user-images.githubusercontent.com/227442/84065396-fd851000-a9cc-11ea-9ba8-47c6a3560d83.png)

**Comment by BostonZcash** [comment]
Thanks. I just switched my iOS region to one that uses the comma as a decimal separator and was able to replicate the same.

The iOS numpad here only allows you to enter whatever the region is set to.

The app should respect whatever the iOS numpad input is using for the separator, and also the `0.0` amount preview should switch based on region.
