### ISSUE TITLE
Transaction computation is unacceptably slow

### ISSUE THREAD

**Issue by rex4539** [zecwalletco/zecwallet-mobile#21]
Waiting for about a minute to compute the transaction is unacceptable in real life commerce.

**Comment by BostonZcash** [comment]
@rex4539 A z2z is taking 18s on a 7th Gen iPod (2019). What model device are you using?

Are you aware of any iOS shielding benchmarks?

**Comment by adityapk00** [comment]
This was recently fixed, it now uses multiple cores to gen a transaction
