### ISSUE TITLE
Start syncing during splash screen

### ISSUE THREAD

**Issue by rex4539** [zecwalletco/zecwallet-mobile#25]
To get a head start, start syncing as soon as the splash screen appears.

If it helps, keep it up for a couple more seconds so hopefully the app is synced by the time the main window appears, if it was just a day or two since the app was last launched.

**Comment by adityapk00** [comment]
Unfortunately this doesn't seem possible, since the splash screen is loading the native library. As soon as the sync starts, the splash screen goes away.
