### ISSUE TITLE
Require choosing authentication method upon wallet creation

### ISSUE THREAD

**Issue by powerkangaroo** [zecwalletco/zecwallet-mobile#28]
When the wallet is generated or imported, require the user to choose one out of these authentication options:

* Password (specific to this app)
* PIN (specific to this app)
* fingerprint
* Default device screen lock protection (PIN, password, pattern, fingerprint, face lock - whichever is enabled)

Once implemented, for users that upgrade from an older version, require them to make this choice when first opening the wallet.

**Comment by adityapk00** [comment]
Duplicate of #17
