### ISSUE TITLE
Frozen on Computing Transaction Page

### ISSUE THREAD

**Issue by afterconnery** [zecwalletco/zecwallet-mobile#33]
Android 7.1.1
Version 1.0.14 from Play Store

Whenever I make a transaction it get stuck on the computing transaction page. I can back out of it, but it takes me back to the form page with all the previous info still typed in. The transaction does not go through.
![Screenshot_20200908-122924](https://user-images.githubusercontent.com/10703247/93263580-f90e8700-f773-11ea-94c1-e0fddf4d2a07.png)

Also, there is not a way for me to get these funds off of my phone onto another Zecwallet. In the Android app I am only given a seed, but opening up Zecwallet full node or Lite (both on desktop) I can only put in private keys. No place for seed phrases. Actually I would be in the same position if I only had the seed phrase for both desktop options because there isn't a place to put the word phrases.

**Comment by adityapk00** [comment]
Thank you for filing this bug. Here's how to recover the seed on the desktop:

1. Download the latest Zecwallet Lite from www.zecwallet.co
2. If you have an existing wallet on the desktop, please move/rename it or back it up. 
  - The wallet file is `zecwallet-light-wallet.dat`, and is in `%APPDATA%/Zcash` folder on Windows and `~/Library/Application Support/Zcash` folder on the Mac
3. Start Zecwallet Lite. You will be asked to create a new wallet or restore. Click Restore
4. Now, you can type in the seed and the birthday to recover your funds.

**Comment by adityapk00** [comment]
Once you have done this, will you be willing to share (privately, of course) the problematic wallet seed so i can debug? You can move all the funds out of the problematic wallet, and then share it with me to see if I can get to the bottom of this issue.

**Comment by adityapk00** [comment]
Also, note that the latest version of the Android app is 1.0.16, so it doesn't appear that you have the latest version. Please update from the play store or download the APK.

**Comment by afterconnery** [comment]
On the Playstore (for me) the latest is 1.0.14. Also, when I restore the wallet I get this: 
![zecwallet-lite](https://user-images.githubusercontent.com/10703247/93315106-a0bda080-f7d8-11ea-8f97-138482dd9415.png)

Once I get access to my wallet I will share the seed with you to see if the problem lies there.

**Comment by adityapk00** [comment]
@afterconnery Can you please try again - There was an unrelated issue with the hosting infra which was causing this error. It should work now.
