### ISSUE TITLE
Add Pin

### ISSUE THREAD

**Issue by afterconnery** [zecwalletco/zecwallet-mobile#4]
Can you add a PIN verification screen for security purpose similar to Green Wallet or even Litecoin's Litewallet?
![Screenshot_20200529-164828~2](https://user-images.githubusercontent.com/10703247/83304297-9eedb400-a1cc-11ea-9e65-c2280ebeca80.png)

**Comment by powerkangaroo** [comment]
I don't see this in the app. It doesn't request neither the phones screen unlocking mechanism, nor does it offer setting a custom PIN.
