### ISSUE TITLE
typos in rescan ui

### ISSUE THREAD

**Issue by petjal** [zecwalletco/zecwallet-mobile#42]
At least two that I can see without looking them up ("i before e", etc):

https://github.com/zecwalletco/zecwallet-mobile/blob/656467a896384ab0fa090d08ed0ddbc05620374a/components/RescanModal.tsx#L51

**Comment by meiskalt7** [comment]
https://github.com/zecwalletco/zecwallet-mobile/pull/43
made a pull request for it
