### ISSUE TITLE
Improvement: automatically trim whitespace in pasted addresses

### ISSUE THREAD

**Issue by BostonZcash** [zecwalletco/zecwallet-mobile#6]
Copying addresses from various sources often results in whitespace within the clipboard contents.

An improvement would be to automatically trim pasted content to the address field of the Send pane.

Otherwise, 'Invalid address' is displayed, which requires the user scrolling and deleting spaces.

**Comment by adityapk00** [comment]
Fixed in 91410b1a917f610076d6ea6fe9309d01020f38ce
