### ISSUE TITLE
Sent transactions do not appear on iOS

### ISSUE THREAD

**Issue by rex4539** [zecwalletco/zecwallet-mobile#9]
100% synced but I can only see received transactions, not sent.

**Comment by rex4539** [comment]
Looks like some sort of UI refresh issue.

I somehow went into the menu, selected to see the Server Info and then when I returned they appeared.

**Comment by BostonZcash** [comment]
I've noticed it not immediately reflecting new TXs within the Transactions pane, sometimes needing to flip around menus or exit and re-enter for them to show (if these actions even have an effect on this). This is on iOS as well as Android.

**Comment by adityapk00** [comment]
Closed in 22d2722
